
package yili.commonservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonServiceSoap", targetNamespace = "CommonService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonServiceSoap {


    /**
     * 查询货品
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QuerySku", action = "CommonService/QuerySku")
    @WebResult(name = "QuerySkuResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QuerySku", targetNamespace = "CommonService", className = "commonservice.QuerySku")
    @ResponseWrapper(localName = "QuerySkuResponse", targetNamespace = "CommonService", className = "commonservice.QuerySkuResponse")
    public String querySku(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 查询入库LPN
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryReceiptLPN", action = "CommonService/QueryReceiptLPN")
    @WebResult(name = "QueryReceiptLPNResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryReceiptLPN", targetNamespace = "CommonService", className = "commonservice.QueryReceiptLPN")
    @ResponseWrapper(localName = "QueryReceiptLPNResponse", targetNamespace = "CommonService", className = "commonservice.QueryReceiptLPNResponse")
    public String queryReceiptLPN(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * LPN收货上架
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReceivingAndPutawayLPN", action = "CommonService/ReceivingAndPutawayLPN")
    @WebResult(name = "ReceivingAndPutawayLPNResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "ReceivingAndPutawayLPN", targetNamespace = "CommonService", className = "commonservice.ReceivingAndPutawayLPN")
    @ResponseWrapper(localName = "ReceivingAndPutawayLPNResponse", targetNamespace = "CommonService", className = "commonservice.ReceivingAndPutawayLPNResponse")
    public String receivingAndPutawayLPN(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 查询生产计划
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryReceiptPlans", action = "CommonService/QueryReceiptPlans")
    @WebResult(name = "QueryReceiptPlansResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryReceiptPlans", targetNamespace = "CommonService", className = "commonservice.QueryReceiptPlans")
    @ResponseWrapper(localName = "QueryReceiptPlansResponse", targetNamespace = "CommonService", className = "commonservice.QueryReceiptPlansResponse")
    public String queryReceiptPlans(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 查询出库任务
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryOutboundTask", action = "CommonService/QueryOutboundTask")
    @WebResult(name = "QueryOutboundTaskResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryOutboundTask", targetNamespace = "CommonService", className = "commonservice.QueryOutboundTask")
    @ResponseWrapper(localName = "QueryOutboundTaskResponse", targetNamespace = "CommonService", className = "commonservice.QueryOutboundTaskResponse")
    public String queryOutboundTask(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 任务接收及完成
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TaskReceivedOrCompleted", action = "CommonService/TaskReceivedOrCompleted")
    @WebResult(name = "TaskReceivedOrCompletedResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "TaskReceivedOrCompleted", targetNamespace = "CommonService", className = "commonservice.TaskReceivedOrCompleted")
    @ResponseWrapper(localName = "TaskReceivedOrCompletedResponse", targetNamespace = "CommonService", className = "commonservice.TaskReceivedOrCompletedResponse")
    public String taskReceivedOrCompleted(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 货位移动
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoveInvLocation", action = "CommonService/MoveInvLocation")
    @WebResult(name = "MoveInvLocationResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "MoveInvLocation", targetNamespace = "CommonService", className = "commonservice.MoveInvLocation")
    @ResponseWrapper(localName = "MoveInvLocationResponse", targetNamespace = "CommonService", className = "commonservice.MoveInvLocationResponse")
    public String moveInvLocation(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 库存调整查询
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvAdjustment", action = "CommonService/QueryInvAdjustment")
    @WebResult(name = "QueryInvAdjustmentResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryInvAdjustment", targetNamespace = "CommonService", className = "commonservice.QueryInvAdjustment")
    @ResponseWrapper(localName = "QueryInvAdjustmentResponse", targetNamespace = "CommonService", className = "commonservice.QueryInvAdjustmentResponse")
    public String queryInvAdjustment(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 库存属性转移查询
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvTransfer", action = "CommonService/QueryInvTransfer")
    @WebResult(name = "QueryInvTransferResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryInvTransfer", targetNamespace = "CommonService", className = "commonservice.QueryInvTransfer")
    @ResponseWrapper(localName = "QueryInvTransferResponse", targetNamespace = "CommonService", className = "commonservice.QueryInvTransferResponse")
    public String queryInvTransfer(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

    /**
     * 库存对账
     * 
     * @param quyPara
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInventory", action = "CommonService/QueryInventory")
    @WebResult(name = "QueryInventoryResult", targetNamespace = "CommonService")
    @RequestWrapper(localName = "QueryInventory", targetNamespace = "CommonService", className = "commonservice.QueryInventory")
    @ResponseWrapper(localName = "QueryInventoryResponse", targetNamespace = "CommonService", className = "commonservice.QueryInventoryResponse")
    public String queryInventory(
        @WebParam(name = "quyPara", targetNamespace = "CommonService")
        String quyPara);

}
